### ISSUE TITLE
polars >= 0.19.7 not buildable on windows azure runners.

### ISSUE THREAD

**Issue by 0xbe7a** [conda-forge/polars-feedstock#183]
As observed during #182 newer versions of Polars require significantly more memory to build compared to older versions. This has led to OOM errors on Azure Pipeline runners for both Linux and Windows.

On Linux, we can mitigate this issue by enabling swapping, but the Windows environment is more challenging to address. Adjusting the system pagefile on Windows doesn't take effect until after a system reboot, which is not practical in this context.

Previous hotfixes (https://github.com/conda-forge/polars-feedstock/commit/e88541f2933153187aef3cccaa52bce0c8a5fccf, https://github.com/conda-forge/polars-feedstock/commit/fb518ca24bf6b174f468afe991ad342cd94417e0) attempted to reduce memory requirements, particularly during the linking phase, by lowering the LTO level. 

One option is to disable LTO entirely on Windows to atleast get Windows building again, although this will almost certainly result in a performance hit.

Another option would be to try to compile Polars for Windows using a Linux runner as a build platform.

Suggestions and insights are welcome.

**Comment by svaningelgem** [comment]
I think it's since version 0.19.4. Because 0.19.3 was the latest version available for windows on conda-forge.

**Comment by 0xbe7a** [comment]
Polars 0.19.4 - 0.19.7 released non buildable source distributions due to a maturin bug (see #179)

**Comment by svaningelgem** [comment]
Thanks for the clarification!

**Comment by jonashaag** [comment]
IMO non-LTO is better than nothing so worth doing short time.

**Comment by 0xbe7a** [comment]
I already tried non LTO, but it was not sufficient to prevent the OOM. I got the cross-build from Linux working today with clang_win-64 but it required some patches to the maturin-, clang-, and rust-activation-feedstock. Hopefully everything will be merged by the end of the week 🤞

**Comment by svaningelgem** [comment]
Thanks a lot @0xbe7a !
