### ISSUE TITLE
Feature request: polars-u64-idx (bigidx) build

### ISSUE THREAD

**Issue by shenker** [conda-forge/polars-feedstock#186]
### Comment:

Just as pypi has a bigidx build, it'd be great if that were available on conda-forge as well.

**Comment by hendrikmakait** [comment]
+1

**Comment by bgianfo** [comment]
I would be happy to help get this setup if someone could point me in the right direction?

**Comment by 0xbe7a** [comment]
Hi @bgianfo, thank you for wanting to contribute to this feedstock. For additional builds with special features, you would add additional outputs to this feedstock that enable the bigidx feature for the build. This feedstock can then create a second package output polars-u64-idx. You can take a look at the tensorflow-feedstock https://github.com/conda-forge/tensorflow-feedstock/blob/main/recipe/meta.yaml as they do. (And probably use every conda-build feature you would ever need, but most of it is not required here)
