### ISSUE TITLE
Add back Python 3.8 support

### ISSUE THREAD

**Issue by baycoder0** [conda-forge/polars-feedstock#268]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Looks like Polars is now longer published in Conda for Python 3.8 starting from 1.6.0. However, the official library still supports Python 3.8 in the newer versions (1.6.0, 1.7.0, 1.7.1, 1.8.0).

could we add back Python 3.8 publishing for Polars in conda-forge?

### Installed packages

```shell
Not relevant, does not work with empty list either
```

### Environment info

```shell
Not relevant (Python version 3.8.19.final.0)
```

**Comment by 0xbe7a** [comment]
Python 3.8 is reaching general EOL in about 7 days, and `conda-forge` already dropped support 1 month ago. See https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/5013.
