### ISSUE TITLE
Big size difference for Linux vs macOS/Windows

### ISSUE THREAD

**Issue by hoxbro** [conda-forge/polars-feedstock#292]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

The size of the Polar package seems to be around 25 MB for macOS and Windows and 100 MB for Linux. 

https://anaconda.org/conda-forge/polars

![Image](https://github.com/user-attachments/assets/1780572e-2e1d-40e8-8317-d03601ec8069)

### Installed packages

```shell
not relevant
```

### Environment info

```shell
not relevant
```

**Comment by pavelzw** [comment]
👀  uncompressed it's 1GB

![Image](https://github.com/user-attachments/assets/e42ae000-fcf4-41d7-9963-5863b77f4fcb)

**Comment by pavelzw** [comment]
the issue started from 1.14.0 onwards, maybe because of https://github.com/conda-forge/polars-feedstock/pull/288
