### ISSUE TITLE
Windows builds go OOM and need to be redone

### ISSUE THREAD

**Issue by timkpaine** [conda-forge/polars-feedstock#95]
This is a known issue and is "resolved" for PRs only by rerunning them until they pass

**Comment by arturdaraujo** [comment]
Maybe @h-vetinari could take a look at that? Have seen this problem before or are you familiar with this? It seems to be recurrent on [polars](https://github.com/pola-rs/polars)-feedstock. 

Relevant: 
- https://github.com/conda-forge/polars-feedstock/issues/96
- https://github.com/conda-forge/polars-feedstock/pull/87
- https://github.com/pola-rs/polars/issues/6624

**Comment by arturdaraujo** [comment]
@timkpaine could you describe in more depth the problem?

**Comment by borchero** [comment]
Since #121 was closed (seemingly) without action, I wanted to kindly ask again whether the Windows builds for 0.17.2 can be retried 😅

**Comment by timkpaine** [comment]
> Since #121 was closed (seemingly) without action, I wanted to kindly ask again whether the Windows builds for 0.17.2 can be retried 😅

Sure, go for it. It's unclear to me how you retrigger the builds, and even if you did, polars is released several times a week. A one time retriggering of an individual release doesn't sound like a valuable exercise vs trying to fix the underlying issue.

**Comment by borchero** [comment]
#129 does not make any meaningful progress either. Since the Linux builds don't seem to be affected: can we use Linux runners to cross-compile the Windows packages? I don't have any experience with setting this up for feedstocks, can someone weigh in here, potentially @xhochy?
